### ISSUE TITLE
New flask app only show 404

### ISSUE THREAD

**Issue by direktornswe** [kuhn-ruess/cmdbsyncer#23]
Idepently if I use the docker container, or if I build the app from source I only get a 404 when visiting the web page, see below 
`(ENV) [root@cmdb-sync cmdbsyncer]# flask run --host 0.0.0.0 --port 8080
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
/root/ENV/lib64/python3.9/site-packages/flask_admin/model/base.py:1415: UserWarning: Fields missing from ruleset: render_full_conditions,render_attribute_outcomes
  warnings.warn(text)
/root/ENV/lib64/python3.9/site-packages/flask_admin/model/base.py:1415: UserWarning: Fields missing from ruleset: render_full_conditions,render_attribute_rewrite
  warnings.warn(text)
/root/ENV/lib64/python3.9/site-packages/flask_admin/model/base.py:1415: UserWarning: Fields missing from ruleset: render_full_conditions,render_checkmk_outcome
  warnings.warn(text)
/root/ENV/lib64/python3.9/site-packages/flask_admin/model/base.py:1415: UserWarning: Fields missing from ruleset: render_full_conditions,render_netbox_outcome
  warnings.warn(text)
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:8080
 * Running on http://10.0.101.103:8080 (Press CTRL+C to quit)
10.0.101.100 - - [08/Jul/2023 18:09:56] "GET / HTTP/1.1" 404 -
10.0.101.100 - - [08/Jul/2023 18:09:56] "GET /favicon.ico HTTP/1.1" 404 -`

**Comment by Bastian-Kuhn** [comment]
I will change that, currently there was on purpose no redirect to /admin but that seams to confuse

**Comment by Bastian-Kuhn** [comment]
Can you try with the current git? That should now redirect you to the admin automatically.
