### ISSUE TITLE
Bug which prevent update of site in netbox

### ISSUE THREAD

**Issue by DWEitscope** [kuhn-ruess/cmdbsyncer#25]
Hi, we found a bug which prevent that the side id is updated when you use a custom attributes rule to set the site on netbox export.

The bug is located in the netbox syncer.py on line 264 to 267
```
            if key.startswith('nb_'):
                key = key[3:]
            if key in payload:
                payload[key] = custom_rules.get(key)
```
`custom_rules` contains the new site id with the key `nb_site` but the key variables is set to the value `site` at that point.
This has the effect, dass the site value from `payload` is removed.

Hope this is enough descriptions for the problem case.

**Comment by Bastian-Kuhn** [comment]
Thank you very much for finding and reporting. It is fixed now.

The Problem was with the manual attributes, everybody else seams to have used the sync :)
