### ISSUE TITLE
sync labels in v3

### ISSUE THREAD

**Issue by orester** [kuhn-ruess/cmdbsyncer#30]
I am currently using latest stable 3.2.5 in docker and was using old 1.3 before .. maybe I am just blind but is there no option for syncing attributes as labels to cmkv2 any more?

Is it via "Create Custom Checkmk Attribute.." or "Create Checkmk-Attribute with Syncer Attributes Value.." ?

AFAIR I would go for "Create Checkmk-Attribute" because labels are an builtin field in the API but I have really no idea.

PS: I tried various options in Action Param but was not really successful. Can you please give me a hand? :)

Danke & lG
Oliver

**Comment by orester** [comment]
I am happy to answer the question by myself (as always :D ) - >  Its just using "CheckMK Filter" for whitelisting attributes as labels :)

**Comment by orester** [comment]
closed

**Comment by orester** [comment]
closed

**Comment by Bastian-Kuhn** [comment]
https://cmdbsyncer.readthedocs.io/en/latest/basics/filter/

Description also here, guess the Docs need an Howto for others with the same Problem. Will do asap :)
