### ISSUE TITLE
cmdbsyncer 3.7b2.13 failed to push to netbox 4.0.11 with KeyError CustomAttributeRule

### ISSUE THREAD

**Issue by h0-online** [kuhn-ruess/cmdbsyncer#39]
Neither Documentation nor the error message is telling what to do to prevent the error attached as screenshot.

![image](https://github.com/user-attachments/assets/e500b871-2263-4ee8-8fe4-6fae76ef6d76)

From my perpective is that the connection was successful but that there is a key missing in cmdbsyncers MongoDB?
What to do?

A pull/import from CMK before was successful, so there are several hosts in cmdbsyncer...

Pls. let me know if you need further information...

**Comment by Bastian-Kuhn** [comment]
Hello,

That was no Documentation Problem but a bug with the Debug Mode in case of missing Cache. It is fixed in the Main branch and the 3.7 branch now. 

Can you please test and confirm?

**Comment by h0-online** [comment]
Works fine now 
![image](https://github.com/user-attachments/assets/852ec6bc-3807-4de2-b590-181cd2152857)
in case of debug_hosts...

**Comment by Bastian-Kuhn** [comment]
Yes, just now the configuration for the Netbox Attributes are missing.
