### ISSUE TITLE
cmdbsyncer 3.7b2.13 failed to push to netbox 4.0.11 with "Cannot create Host"

### ISSUE THREAD

**Issue by h0-online** [kuhn-ruess/cmdbsyncer#40]
unfortunately there is occuring another issue when executing ./cmdbsyncer netbox export_hosts [Netbox-Account]
![image](https://github.com/user-attachments/assets/9134d82f-a1e7-4d19-8cec-34b22d96cb37)
seems to be connection was established from cmdbsyncer to netbox but getting response from netbox that a related object was not found, which should be normal as there are only 3 manually entered test-devices in netbox currently (should be entered as first dump from cmdbsyncer to netbox)

**Comment by Bastian-Kuhn** [comment]
That's no bug, that is the missing configuration. You need to link the attributes you imported to Attributes the Syncer can either create or use in Netbox. It's described in: https://cmdbsyncer.readthedocs.io/en/latest/netbox/ header: _Fields witch need reference_. The Last line of the Error shows the Problem returned from Netbox. Netbox complains that there is no Device Type with ID 1 which is the Fallback ID, if no configuration is Missing. It would be the first Device Type you created manually in Netbox if you don't want them created by Syncer.
