### ISSUE TITLE
Netbox Import Tags

### ISSUE THREAD

**Issue by Kleinrotti** [kuhn-ruess/cmdbsyncer#43]
Hi, is it possible to import the tags of devices from netbox to CMDB Syncer?
I want to do something like, if a device in netbox has some tag it will be monitored and exported to CheckMK.

**Comment by Bastian-Kuhn** [comment]
Hi, the current Git Version has a complete new Netbox Implementation using the Netbox SDK (pynetbox).
In this Version the tags should all be there, since there every Attribute of the Device is imported.

**Comment by Kleinrotti** [comment]
Great, the current git version looks good. But I had one error while importing Netbox devices:
![image](https://github.com/user-attachments/assets/fc5cc417-ce0f-47ec-9100-656acecf10da)

Seems like if there are unnamed devices the import stops:
![image](https://github.com/user-attachments/assets/a0def32b-e7c8-4cac-ac5f-a527e762d6c3)

**Comment by Bastian-Kuhn** [comment]
The only thing I can do is to ignore these. Without a name, it's of no use, since Hostname is the Key Identifier in Syncer ans also as well in Checkmk. Just pushed a possible fix.
