### ISSUE TITLE
Labels in checkmk getting added but removed at next sync/export

### ISSUE THREAD

**Issue by Kleinrotti** [kuhn-ruess/cmdbsyncer#44]
Hi,

I currently have the problem that I want to add a label to hosts.
This works so far. But every second sync to checkmk the labels getting removed.
In the next sync they are added back and so on.
Maybe I have something wrong configured?
I use the current git version.
![image](https://github.com/user-attachments/assets/a94c436c-7b11-42be-86da-ed7fa8b187c8)

![image](https://github.com/user-attachments/assets/2957f6d2-ea83-4940-9619-957c52844e1b)

Output from sync when labels are added:
``` -- Start Sync
* Console0001
 * Add to Bulk Update List for update_attributes update
* Console0002
 * Add to Bulk Update List for update_attributes update
* Console0003
 * Add to Bulk Update List for update_attributes update
  3/3 Handling Checkmk Actions ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
 * Send Bulk Update Request 1/1
 -- Check if we need to handle Clusters
 -- Check if we need to cleanup hosts
 -- Check if we need to update Folders
```

Output from sync when labels get removed:
```-- Start Sync
* Console0001
 * Add to Bulk Update List for update_attributes update
 * Add to Bulk Update List for labels update
* Console0002
 * Add to Bulk Update List for update_attributes update
 * Add to Bulk Update List for labels update
* Console0003
 * Add to Bulk Update List for update_attributes update
 * Add to Bulk Update List for labels update
  3/3 Handling Checkmk Actions ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
 * Send Bulk Update Request 1/1
 -- Check if we need to handle Clusters
 -- Check if we need to cleanup hosts
 -- Check if we need to update Folders
```

**Comment by Bastian-Kuhn** [comment]
Hi,

Labels are added automatically if whitelisted in filters.
So the Attributes you have on your host, you either rewrite them to other names, and then whitelist them,
or just whitelist them and they end as labels.

The Attribute Rules are just for Real Attributes, Custom Attributes, Tags and such.

**Comment by Kleinrotti** [comment]
Thanks, that was my mistake. With the whitelist it works as expected :)
